version: '3.8'

networks:
  sistema-bancario:

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: sistemaBancario
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin.01
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sistema-bancario

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
    networks:
      - sistema-bancario

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    restart: always
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - sistema-bancario

  cliente:
    build: ./cliente
    container_name: cliente
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - kafka
    networks:
      - sistema-bancario

  cuenta:
    build: ./cuenta
    container_name: cuenta
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - kafka
    networks:
      - sistema-bancario

volumes:
  postgres-data:
