spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/sistemaBancario
    username: admin
    password: admin.01
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            noncontextual_creation: 'true'
    hibernate:
      ddl-auto: update
  application:
    name: cuenta
server:
  port: '8082'

kafka:
  bootstrap-servers: kafka:9092
  topic:
    cliente-creado: cliente-creado
    cuenta-creada: cuenta-creada
    movimiento-creado: movimiento-creado
    movimiento-error: movimiento-error